service: meka-boilerplate

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  greedy:
    name: "meka-boilerplate-greedy"
    handler: handler.greedy
  random:
    name: "meka-boilerplate-random"
    handler: handler.random

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "yarn"
    includeModules: true
  serverless-offline:
    port: 3002
